// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: gameQueries.sql

package db

import (
	"context"
)

const getGameByID = `-- name: GetGameByID :one
SELECT id, name, provider, category, rtp, variance, enabled, launch_date, tags, image_url
FROM games
WHERE id = ?
`

func (q *Queries) GetGameByID(ctx context.Context, id string) (Game, error) {
	row := q.db.QueryRowContext(ctx, getGameByID, id)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Category,
		&i.Rtp,
		&i.Variance,
		&i.Enabled,
		&i.LaunchDate,
		&i.Tags,
		&i.ImageUrl,
	)
	return i, err
}

const upsertGame = `-- name: UpsertGame :one
INSERT INTO games (
    id, name, provider, category, rtp, variance, enabled, launch_date, tags, image_url
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    provider = EXCLUDED.provider,
    category = EXCLUDED.category,
    rtp = EXCLUDED.rtp,
    variance = EXCLUDED.variance,
    enabled = EXCLUDED.enabled,
    launch_date = EXCLUDED.launch_date,
    tags = EXCLUDED.tags,
    image_url = EXCLUDED.image_url
RETURNING id, name, provider, category, rtp, variance, enabled, launch_date, tags, image_url
`

type UpsertGameParams struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Provider   string  `json:"provider"`
	Category   string  `json:"category"`
	Rtp        float64 `json:"rtp"`
	Variance   string  `json:"variance"`
	Enabled    bool    `json:"enabled"`
	LaunchDate string  `json:"launch_date"`
	Tags       string  `json:"tags"`
	ImageUrl   string  `json:"image_url"`
}

// Inserts a new game or updates an existing one based on the ID.
func (q *Queries) UpsertGame(ctx context.Context, arg UpsertGameParams) (Game, error) {
	row := q.db.QueryRowContext(ctx, upsertGame,
		arg.ID,
		arg.Name,
		arg.Provider,
		arg.Category,
		arg.Rtp,
		arg.Variance,
		arg.Enabled,
		arg.LaunchDate,
		arg.Tags,
		arg.ImageUrl,
	)
	var i Game
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Provider,
		&i.Category,
		&i.Rtp,
		&i.Variance,
		&i.Enabled,
		&i.LaunchDate,
		&i.Tags,
		&i.ImageUrl,
	)
	return i, err
}
