// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingestionLogsQueries.sql

package db

import (
	"context"
)

const getIngestionLog = `-- name: GetIngestionLog :one
SELECT id, source_url, status, ingested_at
FROM ingestion_logs
WHERE source_url = ? LIMIT 1
`

// Retrieves a specific log to check if it has already succeeded.
func (q *Queries) GetIngestionLog(ctx context.Context, sourceUrl string) (IngestionLog, error) {
	row := q.db.QueryRowContext(ctx, getIngestionLog, sourceUrl)
	var i IngestionLog
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Status,
		&i.IngestedAt,
	)
	return i, err
}

const startIngestion = `-- name: StartIngestion :one
INSERT INTO ingestion_logs (source_url, status)
VALUES (?, 'PENDING')
ON CONFLICT (source_url) 
DO UPDATE SET 
    status = EXCLUDED.status,
    ingested_at = CURRENT_TIMESTAMP
RETURNING id, source_url, status, ingested_at
`

// Inserts a new PENDING log, or resets an existing one to PENDING if it previously FAILED.
func (q *Queries) StartIngestion(ctx context.Context, sourceUrl string) (IngestionLog, error) {
	row := q.db.QueryRowContext(ctx, startIngestion, sourceUrl)
	var i IngestionLog
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.Status,
		&i.IngestedAt,
	)
	return i, err
}

const updateIngestionStatus = `-- name: UpdateIngestionStatus :exec
UPDATE ingestion_logs
SET 
    status = ?2, 
    ingested_at = CURRENT_TIMESTAMP
WHERE source_url = ?1
`

type UpdateIngestionStatusParams struct {
	SourceUrl string `json:"source_url"`
	Status    string `json:"status"`
}

// Marks the ingestion as SUCCESS or FAILED once the worker finishes.
func (q *Queries) UpdateIngestionStatus(ctx context.Context, arg UpdateIngestionStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateIngestionStatus, arg.SourceUrl, arg.Status)
	return err
}
