// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type Game struct {
	ID         string  `json:"id"`
	Name       string  `json:"name"`
	Provider   string  `json:"provider"`
	Category   string  `json:"category"`
	Rtp        float64 `json:"rtp"`
	Variance   string  `json:"variance"`
	Enabled    bool    `json:"enabled"`
	LaunchDate string  `json:"launch_date"`
	Tags       string  `json:"tags"`
	ImageUrl   string  `json:"image_url"`
}

type IngestionLog struct {
	ID         int64        `json:"id"`
	SourceUrl  string       `json:"source_url"`
	Status     string       `json:"status"`
	IngestedAt sql.NullTime `json:"ingested_at"`
}
