// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	// Retrieves a specific log to check if it has already succeeded.
	GetIngestionLog(ctx context.Context, sourceUrl string) (IngestionLog, error)
	// Inserts a new PENDING log, or resets an existing one to PENDING if it previously FAILED.
	StartIngestion(ctx context.Context, sourceUrl string) (IngestionLog, error)
	// Marks the ingestion as SUCCESS or FAILED once the worker finishes.
	UpdateIngestionStatus(ctx context.Context, arg UpdateIngestionStatusParams) error
	// Inserts a new game or updates an existing one based on the ID.
	UpsertGame(ctx context.Context, arg UpsertGameParams) (Game, error)
}

var _ Querier = (*Queries)(nil)
